# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(863, 523)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Attention = QtWidgets.QLabel(self.centralwidget)
        self.Attention.setGeometry(QtCore.QRect(10, 0, 241, 121))
        self.Attention.setObjectName("Attention")
        self.comboBox_Mode = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_Mode.setGeometry(QtCore.QRect(30, 130, 101, 31))
        self.comboBox_Mode.setObjectName("comboBox_Mode")
        self.comboBox_Mode.addItem("")
        self.comboBox_Mode.addItem("")
        self.pbtGetMnist = QtWidgets.QPushButton(self.centralwidget)
        self.pbtGetMnist.setEnabled(True)
        self.pbtGetMnist.setGeometry(QtCore.QRect(40, 180, 75, 23))
        self.pbtGetMnist.setObjectName("pbtGetMnist")
        self.pbtClear = QtWidgets.QPushButton(self.centralwidget)
        self.pbtClear.setGeometry(QtCore.QRect(40, 220, 75, 23))
        self.pbtClear.setObjectName("pbtClear")
        self.pbtPredict = QtWidgets.QPushButton(self.centralwidget)
        self.pbtPredict.setGeometry(QtCore.QRect(40, 260, 75, 23))
        self.pbtPredict.setObjectName("pbtPredict")
        self.lbResult = QtWidgets.QLabel(self.centralwidget)
        self.lbResult.setGeometry(QtCore.QRect(10, 310, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        self.lbResult.setFont(font)
        self.lbResult.setObjectName("lbResult")
        self.Result = QtWidgets.QLabel(self.centralwidget)
        self.Result.setGeometry(QtCore.QRect(20, 340, 111, 31))
        self.Result.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Result.setText("")
        self.Result.setObjectName("Result")
        self.lbMnist = QtWidgets.QLabel(self.centralwidget)
        self.lbMnist.setGeometry(QtCore.QRect(270, 10, 91, 16))
        self.lbMnist.setObjectName("lbMnist")
        self.MnistShow = QtWidgets.QLabel(self.centralwidget)
        self.MnistShow.setGeometry(QtCore.QRect(300, 30, 211, 211))
        self.MnistShow.setFrameShape(QtWidgets.QFrame.Box)
        self.MnistShow.setText("")
        self.MnistShow.setObjectName("MnistShow")
        self.lbWrite = QtWidgets.QLabel(self.centralwidget)
        self.lbWrite.setGeometry(QtCore.QRect(150, 250, 61, 16))
        self.lbWrite.setObjectName("lbWrite")
        self.WriteShow = QtWidgets.QLabel(self.centralwidget)
        self.WriteShow.setGeometry(QtCore.QRect(160, 280, 691, 191))
        self.WriteShow.setFrameShape(QtWidgets.QFrame.Box)
        self.WriteShow.setText("")
        self.WriteShow.setObjectName("WriteShow")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(160, 280, 691, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 863, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBox_Mode.activated['QString'].connect(MainWindow.cbBox_Mode_Callback)
        self.pbtClear.clicked.connect(MainWindow.pbtClear_Callback)
        self.pbtPredict.clicked.connect(MainWindow.pbtPredict_Callback)
        self.pbtGetMnist.clicked.connect(MainWindow.pbtGetMnist_Callback)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "手写数字识别GUI最终版 --NJU TJ"))
        self.Attention.setText(_translate("MainWindow", "使用指南：\n"
"^1.本应用内置有两种模式:\n"
"    Mode1: 抽取Mnist数据集图片进行预测\n"
"    Mode2:使用者手写数字进行预测\n"
"^2.在画板范围内,支持多数字书写与识别\n"
"    (不支持数字间连笔书写)\n"
"^3.预测结果将显示在下方方框中\n"
"^4.点击“识别”按钮方可识别"))
        self.comboBox_Mode.setItemText(0, _translate("MainWindow", "1.Mnist数据集"))
        self.comboBox_Mode.setItemText(1, _translate("MainWindow", "2.手写数字"))
        self.pbtGetMnist.setText(_translate("MainWindow", "抽取数据"))
        self.pbtClear.setText(_translate("MainWindow", "清除"))
        self.pbtPredict.setText(_translate("MainWindow", "识别"))
        self.lbResult.setText(_translate("MainWindow", "识别结果："))
        self.lbMnist.setText(_translate("MainWindow", "Mnist抽取区域："))
        self.lbWrite.setText(_translate("MainWindow", "手写区域："))
